<?php

namespace Database\Seeders;

use App\Enums\Difficulty;
use App\Models\Question;
use App\Models\Answer;
use Illuminate\Database\Seeder;

class ChristmasQuestionsSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            ['Qual figura tradicional enfeita o topo de uma árvore de Natal?', ['Estrela', 'Boneco de neve', 'Guirlanda', 'Sino'], 0],
            ['Qual personagem é conhecido por entregar presentes na noite de Natal?', ['Papai Noel', 'Coelhinho da Páscoa', 'Duende', 'Boneco de Neve'], 0],
            ['Em que mês comemoramos o Natal?', ['Dezembro', 'Janeiro', 'Março', 'Novembro'], 0],
            ['Qual é a data do Natal?', ['25 de dezembro', '31 de dezembro', '24 de dezembro', '1º de janeiro'], 0],
            ['Como se chama a canção natalina que fala de sinos?', ['Jingle Bells', 'Silent Night', 'Noite Feliz', 'Alegria do Natal'], 0],
            ['Qual é o nome da rena mais famosa do trenó do Papai Noel?', ['Rudolph', 'Prancer', 'Dasher', 'Blitzen'], 0],
            ['O que representa a estrela no topo da árvore de Natal?', ['A estrela que guiou os Reis Magos', 'A lua cheia', 'A estrela cadente', 'A estrela do mar'], 0],
            ['O que significa a palavra “Natal”?', ['Nascimento', 'Festa', 'Alegria', 'Família'], 0],
            ['Qual cor é tradicionalmente associada ao Natal?', ['Vermelho', 'Azul', 'Amarelo', 'Preto'], 0],
            ['O que muitas pessoas colocam embaixo da árvore de Natal?', ['Presentes', 'Sapatos', 'Cartas', 'Flores'], 0],
            ['Quantas renas tradicionalmente puxam o trenó do Papai Noel?', ['Nove', 'Oito', 'Sete', 'Dez'], 0],
            ['Qual país é considerado a origem da tradição da árvore de Natal?', ['Alemanha', 'EUA', 'Inglaterra', 'França'], 0],
            ['Qual bebida quente é típica no Natal de países frios?', ['Chocolate quente', 'Refrigerante', 'Suco de laranja', 'Água'], 0],
            ['Qual acessório é pendurado na lareira para receber presentes?', ['Meia', 'Chapéu', 'Cachecol', 'Cesta'], 0],
            ['Qual é o nome em inglês do Papai Noel?', ['Santa Claus', 'Father Christmas', 'Saint Merry', 'Red Man'], 0],
            ['Onde Papai Noel mora segundo a tradição?', ['Polo Norte', 'Finlândia', 'Suécia', 'Groenlândia'], 0],
            ['Que doce é comum em árvores de Natal?', ['Bengala doce', 'Bala de goma', 'Pirulito', 'Chocolate'], 0],
            ['Qual animal costuma acompanhar cenas de presépio?', ['Burro', 'Coelho', 'Cachorro', 'Gato'], 0],
            ['Quantos Reis Magos visitaram o Menino Jesus?', ['Três', 'Dois', 'Quatro', 'Cinco'], 0],
            ['Como se chama a véspera de Natal?', ['Noite de Natal', 'Noite Feliz', 'Festa de Natal', 'Véspera de Ano Novo'], 0],
            ['Qual canção natalina tem a frase “Bate o sino pequenino”?', ['Bate o sino', 'Jingle Bells', 'Silent Night', 'Deck the Halls'], 0],
            ['Qual flor vermelha é típica do Natal?', ['Poinsétia', 'Rosa', 'Lírio', 'Margarida'], 0],
            ['Qual fruta seca costuma estar presente em panetones?', ['Uva passa', 'Banana', 'Maçã', 'Damasco'], 0],
            ['Qual sobremesa tradicional acompanha a ceia de Natal no Brasil?', ['Rabanada', 'Sorvete', 'Bolo de cenoura', 'Pudim de chocolate'], 0],
            ['Qual música começa com “Noite feliz, noite de paz”?', ['Noite Feliz', 'Jingle Bells', 'Alegria de Natal', 'Feliz Ano Novo'], 0],
            ['Qual o nome da ceia servida na noite do dia 24?', ['Ceia de Natal', 'Ceia de Ano Novo', 'Jantar de Inverno', 'Banquete'], 0],
            ['Que alimento não pode faltar na ceia de Natal brasileira?', ['Chester', 'Pizza', 'Sushi', 'Lasanha'], 0],
            ['Que símbolo natalino é feito de galhos e pendurado na porta?', ['Guirlanda', 'Laço', 'Coroa de flores', 'Meia'], 0],
            ['Em que parte do mundo o Natal costuma ter neve?', ['Hemisfério Norte', 'Hemisfério Sul', 'Equador', 'África'], 0],
            ['Qual personagem ajuda Papai Noel?', ['Duendes', 'Fadas', 'Elfos Negros', 'Bruxas'], 0],
            ['Qual nome se dá ao boneco feito de neve?', ['Frosty', 'Jack', 'Snowtoy', 'Olaf'], 0],
            ['O que se costuma dizer quando alguém espirra no Natal?', ['Saúde!', 'Ho ho ho!', 'Feliz Natal!', 'Deus abençoe!'], 0],
            ['Qual música fala sobre trenós correndo na neve?', ['Jingle Bells', 'Bate o Sino', 'White Christmas', 'Noite Feliz'], 0],
            ['O que simboliza a vela no Natal?', ['Luz de Cristo', 'Anjo', 'Presente', 'Neve'], 0],
            ['O que simboliza o presépio?', ['Nascimento de Jesus', 'Festa da Família', 'Neve', 'Trenó'], 0],
            ['Qual fruta tropical muitos brasileiros usam na decoração de Natal?', ['Uva', 'Abacaxi', 'Banana', 'Mamão'], 0],
            ['O que representa o sino no Natal?', ['Anúncio da boa nova', 'Festa', 'Neve', 'Alegria'], 0],
            ['Qual música tem “ho ho ho” como marca?', ['Santa Claus is coming to town', 'Jingle Bells', 'Frosty', 'We wish you a Merry Christmas'], 0],
            ['Qual personagem natalino tem barba branca e roupa vermelha?', ['Papai Noel', 'Duende', 'Anjo', 'Boneco de Neve'], 0],
            ['O que se deseja ao dizer “Feliz Natal”?', ['Alegria e amor', 'Dinheiro', 'Paz mundial apenas', 'Chocolate'], 0],
            ['Qual a data da virada do ano?', ['31 de dezembro', '25 de dezembro', '30 de dezembro', '1º de janeiro'], 0],
            ['O que as pessoas costumam fazer à meia-noite do Ano Novo?', ['Soltar fogos', 'Dormir', 'Trabalhar', 'Comer chocolate'], 0],
            ['Qual cor é tradicionalmente usada no Réveillon para atrair paz?', ['Branco', 'Vermelho', 'Azul', 'Amarelo'], 0],
            ['Qual bebida é tradicional na virada?', ['Espumante', 'Suco', 'Refrigerante', 'Água'], 0],
            ['Qual é a primeira data do ano?', ['1º de janeiro', '31 de dezembro', '2 de janeiro', '5 de janeiro'], 0],
            ['Qual é o nome da festa que celebra a chegada de um novo ano?', ['Réveillon', 'Natal', 'Carnaval', 'Festa Junina'], 0],
            ['Qual superstição envolve pular ondas?', ['Boa sorte', 'Dinheiro', 'Saúde', 'Amor'], 0],
            ['O que significa “Réveillon”?', ['Recomeço', 'Festa', 'Luz', 'Natal'], 0],
            ['Qual é o nome da contagem regressiva?', ['Countdown', 'Timer', 'Start', 'Zero'], 0],
            ['O que as pessoas costumam fazer para começar bem o ano?', ['Fazer promessas', 'Dormir', 'Brigar', 'Viajar'], 0],
            ['Que alimento redondo simboliza prosperidade?', ['Lentilha', 'Feijão', 'Arroz', 'Pão'], 0],
            ['Quantos segundos tem a contagem regressiva tradicional?', ['10', '5', '20', '60'], 0],
            ['Qual flor é comum nas festas de fim de ano?', ['Lírio branco', 'Girassol', 'Tulipa', 'Cravo'], 0],
            ['Qual destino no Brasil é famoso pelas festas de Ano Novo?', ['Copacabana', 'Florianópolis', 'Fortaleza', 'Gramado'], 0],
            ['O que simboliza a queima de fogos?', ['Luz e alegria', 'Barulho', 'Tradição', 'Força'], 0],
            ['O que muitos fazem para atrair dinheiro?', ['Usar amarelo', 'Cantar', 'Fazer bolo', 'Dormir'], 0],
            ['O que significa usar vermelho no Ano Novo?', ['Paixão', 'Tristeza', 'Alegria', 'Trabalho'], 0],
            ['O que se deseja quando se diz “Feliz Ano Novo”?', ['Prosperidade', 'Tristeza', 'Fim de festa', 'Silêncio'], 0],
            ['O que significa a uva na virada?', ['Boa sorte', 'Presente', 'Natal', 'Alegria'], 0],
            ['Qual santo é celebrado no dia 1º de janeiro?', ['Santa Maria, Mãe de Deus', 'São José', 'São João', 'São Pedro'], 0],
            ['Onde é comemorado o Natal com fogos de artifício e praia?', ['Brasil', 'Rússia', 'Suécia', 'Noruega'], 0],
            ['Em que estação do ano acontece o Natal no Brasil?', ['Verão', 'Inverno', 'Outono', 'Primavera'], 0],
            ['Qual país é famoso pelos mercados de Natal?', ['Alemanha', 'Brasil', 'Egito', 'Chile'], 0],
            ['Qual é a língua original da música “Noite Feliz”?', ['Alemão', 'Inglês', 'Português', 'Latim'], 0],
            ['O que as crianças costumam deixar para Papai Noel?', ['Biscoitos e leite', 'Pizza', 'Café', 'Chá'], 0],
            ['Quem costuma ajudar Papai Noel a fazer brinquedos?', ['Duendes', 'Fadas', 'Anjos', 'Soldados'], 0],
            ['Qual país popularizou o Papai Noel moderno?', ['Estados Unidos', 'Brasil', 'Rússia', 'Portugal'], 0],
            ['Qual elemento natural costuma ser usado para enfeitar portas?', ['Guirlanda de pinheiros', 'Coroa de rosas', 'Bola de futebol', 'Lenha'], 0],
            ['O que se costuma escrever em cartões natalinos?', ['Mensagens de amor e paz', 'Piadas', 'Receitas', 'Reclamações'], 0],
            ['O que simboliza a neve nas festas de Natal?', ['Pureza e renovação', 'Fome', 'Medo', 'Escuridão'], 0],
            ['Quantas cores têm os tradicionais bastões doces natalinos?', ['Duas (vermelho e branco)', 'Uma', 'Três', 'Cinco'], 0],
            ['Qual comida é comum na ceia americana de Natal?', ['Peru', 'Chester', 'Tacos', 'Sushi'], 0],
            ['Qual é o nome do trenó mágico do Papai Noel?', ['Sleigh', 'Snowcar', 'Magic', 'Winter Ride'], 0],
            ['O que simboliza o presente de Natal?', ['Amor e generosidade', 'Dinheiro', 'Comida', 'Trabalho'], 0],
            ['Quem visita as crianças que se comportam mal segundo a lenda europeia?', ['Krampus', 'Duende do mal', 'Coelho', 'Gato'], 0],
            ['Qual país originou o panetone?', ['Itália', 'Brasil', 'EUA', 'Alemanha'], 0],
            ['Qual fruta representa abundância no Ano Novo?', ['Uva', 'Laranja', 'Banana', 'Maçã'], 0],
            ['O que simboliza o fogo na virada do ano?', ['Purificação', 'Alegria', 'Medo', 'Escuridão'], 0],
            ['Qual continente comemora Natal com neve e lareira?', ['Europa', 'África', 'América do Sul', 'Oceania'], 0],
            ['Qual é a tradução de “Merry Christmas”?', ['Feliz Natal', 'Bom Ano', 'Feliz Aniversário', 'Bom feriado'], 0],
            ['Qual é a cor tradicional das velas de Natal?', ['Vermelho', 'Azul', 'Branco', 'Verde'], 0],
            ['Que tipo de árvore é mais usada como árvore de Natal?', ['Pinheiro', 'Carvalho', 'Eucalipto', 'Cedro'], 0],
            ['Qual fruta costuma enfeitar mesas de Natal no Brasil?', ['Uva', 'Manga', 'Abacaxi', 'Banana'], 0],
            ['Qual sobremesa gelada é comum nas festas de fim de ano no Brasil?', ['Sorvete', 'Torta de maçã', 'Bolo inglês', 'Panetone'], 0],
            ['Em que país surgiu o panetone?', ['Itália', 'França', 'Alemanha', 'Portugal'], 0],
            ['Quem ajuda Papai Noel a fazer brinquedos?', ['Duendes', 'Renas', 'Anjos', 'Bonecos de Neve'], 0],
            ['Qual bebida é mais servida em ceias de Ano Novo?', ['Espumante', 'Cerveja', 'Suco de uva', 'Refrigerante'], 0],
            ['Que flor é símbolo de Natal?', ['Poinsétia', 'Lírio', 'Rosa', 'Margarida'], 0],
            ['Qual cor representa esperança no Ano Novo?', ['Verde', 'Amarelo', 'Branco', 'Azul'], 0],
            ['Em que dia as pessoas desmontam a árvore de Natal tradicionalmente?', ['06 de janeiro', '02 de janeiro', '01 de janeiro', '31 de dezembro'], 0],
            ['Qual animal costuma estar presente no presépio?', ['Burro', 'Gato', 'Coelho', 'Cachorro'], 0],
            ['Qual alimento representa fartura no Ano Novo?', ['Lentilha', 'Feijão', 'Arroz', 'Pão'], 0],
            ['Qual país é conhecido por seus mercados de Natal?', ['Alemanha', 'Brasil', 'EUA', 'Portugal'], 0],
            ['O que simboliza a estrela de Natal?', ['A estrela que guiou os Reis Magos', 'Boa sorte', 'Paz mundial', 'Alegria'], 0],
            ['Qual música natalina é mais popular no mundo?', ['Jingle Bells', 'Noite Feliz', 'Bate o Sino', 'Deck the Halls'], 0],
            ['Qual fruta é símbolo de prosperidade no Ano Novo?', ['Uva', 'Banana', 'Maçã', 'Abacaxi'], 0],
            ['Quantos Reis Magos visitaram Jesus?', ['Três', 'Dois', 'Quatro', 'Cinco'], 0],
            ['Qual é a cor da roupa tradicional de Papai Noel?', ['Vermelha', 'Verde', 'Branca', 'Azul'], 0],
            ['O que se costuma colocar embaixo da árvore de Natal?', ['Presentes', 'Flores', 'Bolas', 'Luzes'], 0],
            ['Qual a principal refeição da noite de Natal?', ['Ceia', 'Jantar simples', 'Almoço', 'Lanche'], 0],
            ['Qual é a flor símbolo das festas natalinas?', ['Poinsétia', 'Girassol', 'Margarida', 'Orquídea'], 0],
            ['Qual o nome em inglês para “Noite Feliz”?', ['Silent Night', 'Holy Night', 'Merry Night', 'Christmas Night'], 0],
            ['Qual personagem tem barba branca e gorro vermelho?', ['Papai Noel', 'Krampus', 'Duende', 'Boneco de Neve'], 0],
            ['Qual cor representa paixão no Réveillon?', ['Vermelho', 'Branco', 'Amarelo', 'Verde'], 0],
            ['Em qual estação ocorre o Natal no Brasil?', ['Verão', 'Inverno', 'Primavera', 'Outono'], 0],
            ['Que fruta costuma enfeitar mesas de Ano Novo?', ['Uva', 'Banana', 'Pêssego', 'Manga'], 0],
            ['Qual personagem lendário distribui presentes no Natal?', ['Papai Noel', 'Coelhinho', 'Rei Mago', 'Duende'], 0],
            ['Qual país tem tradição de colocar sapatos na janela para presentes?', ['Holanda', 'Brasil', 'EUA', 'Alemanha'], 0],
            ['Quantas cores tem o bastão doce natalino?', ['Duas', 'Três', 'Quatro', 'Uma'], 0],
            ['Qual som é típico do Natal?', ['Sinos', 'Tambores', 'Gongos', 'Violão'], 0],
            ['O que é tradicional comer no Ano Novo no Brasil?', ['Lentilha', 'Sushi', 'Hambúrguer', 'Pizza'], 0],
            ['Qual fruta tropical é comum nas festas de Natal no Brasil?', ['Abacaxi', 'Laranja', 'Banana', 'Caju'], 0],
            ['O que simboliza a guirlanda na porta?', ['Boas-vindas', 'Riqueza', 'Amor', 'Fé'], 0],
            ['Qual é a cor mais tradicional do Natal?', ['Vermelho', 'Azul', 'Roxo', 'Preto'], 0],
            ['Quem é o “bom velhinho”?', ['Papai Noel', 'Rei Mago', 'Coelho', 'Anjo'], 0],
            ['Qual música tem a frase “ho ho ho”?', ['Santa Claus is Coming to Town', 'Jingle Bells', 'Noite Feliz', 'Frosty'], 0],
            ['O que representa o fogo no Ano Novo?', ['Purificação', 'Guerra', 'Inverno', 'Luz de velas'], 0],
            ['Onde Papai Noel mora?', ['Polo Norte', 'Alasca', 'Finlândia', 'Groenlândia'], 0],
            ['Qual bebida quente é comum em países frios no Natal?', ['Chocolate quente', 'Café', 'Chá verde', 'Leite'], 0],
            ['O que representa a luz das velas?', ['Luz de Cristo', 'Verão', 'Alegria', 'Sol'], 0],
            ['Qual sobremesa é típica no Natal no Brasil?', ['Rabanada', 'Torta de morango', 'Bolo de chocolate', 'Sorvete'], 0],
            ['O que simboliza o presépio?', ['Nascimento de Jesus', 'Neve', 'Árvore', 'Trenó'], 0],
            ['O que simboliza o sino natalino?', ['Anúncio da boa nova', 'Festa', 'Alegria', 'Som bonito'], 0],
            ['Quem visita crianças malcomportadas na lenda europeia?', ['Krampus', 'Duende do mal', 'Boneco de neve', 'Anjo'], 0],
            ['Qual nome em inglês significa “Feliz Natal”?', ['Merry Christmas', 'Happy Christmas', 'Lovely Christmas', 'Good Christmas'], 0],
            ['Qual país originou a árvore de Natal?', ['Alemanha', 'Brasil', 'Inglaterra', 'EUA'], 0],
            ['Quantas renas puxam o trenó de Papai Noel?', ['Nove', 'Oito', 'Sete', 'Dez'], 0],
            ['Qual a fruta símbolo de abundância no Ano Novo?', ['Uva', 'Maçã', 'Banana', 'Pêssego'], 0],
            ['Qual dia é comemorado o Ano Novo?', ['1º de janeiro', '31 de dezembro', '25 de dezembro', '2 de janeiro'], 0],
            ['Qual flor vermelha enfeita casas no Natal?', ['Poinsétia', 'Tulipa', 'Girassol', 'Lírio'], 0],
            ['O que significa “Natal”?', ['Nascimento', 'Paz', 'Felicidade', 'Festa'], 0],
            ['Qual país popularizou o Papai Noel moderno?', ['EUA', 'Brasil', 'Alemanha', 'Portugal'], 0],
            ['Qual fruta é usada na decoração de festas de fim de ano?', ['Uva', 'Manga', 'Melancia', 'Pera'], 0],
            ['O que as pessoas fazem à meia-noite do Ano Novo?', ['Soltam fogos', 'Dormem', 'Trabalham', 'Vão à praia'], 0],
            ['Quem canta “ho ho ho”?', ['Papai Noel', 'Duendes', 'Renas', 'Reis Magos'], 0],
            ['Qual estação do ano é o Natal no hemisfério norte?', ['Inverno', 'Verão', 'Outono', 'Primavera'], 0],
            ['O que se deseja ao dizer “Feliz Ano Novo”?', ['Prosperidade', 'Alegria', 'Sorte', 'Saúde'], 0],
            ['Qual país celebra o Natal com neve e lareira?', ['Alemanha', 'Brasil', 'Austrália', 'África do Sul'], 0],
            ['Qual personagem lendário usa trenó e renas?', ['Papai Noel', 'Duende', 'Rei Mago', 'Anjo'], 0],
            ['Qual cor representa dinheiro no Réveillon?', ['Amarelo', 'Verde', 'Azul', 'Rosa'], 0],
            ['O que simboliza a árvore de Natal?', ['Vida', 'Riqueza', 'Alegria', 'Festa'], 0],
            ['O que as crianças deixam para Papai Noel comer?', ['Biscoitos e leite', 'Pão', 'Chocolate', 'Frutas'], 0],
            ['Qual animal puxa o trenó do Papai Noel?', ['Rena', 'Cachorro', 'Cavalo', 'Burro'], 0],
            ['Qual canção tem sinos e trenós?', ['Jingle Bells', 'Noite Feliz', 'Frosty', 'Let it Snow'], 0],
            ['Onde as pessoas pulam ondas no Réveillon?', ['Praia', 'Igreja', 'Rua', 'Shopping'], 0],
            ['O que significa “Réveillon”?', ['Recomeço', 'Natal', 'Festa', 'Fogueira'], 0],
            ['O que simboliza o presente de Natal?', ['Amor', 'Riqueza', 'Alegria', 'Comida'], 0],
            ['Qual país criou o panetone?', ['Itália', 'Brasil', 'EUA', 'Alemanha'], 0],
            ['O que representa a cor azul no Ano Novo?', ['Harmonia', 'Dinheiro', 'Amor', 'Paixão'], 0],
            ['O que representa a cor branca no Réveillon?', ['Paz', 'Amor', 'Alegria', 'Riqueza'], 0],
            ['O que representa a vela de Natal?', ['Luz de Cristo', 'Presente', 'Esperança', 'Neve'], 0],
            ['O que simboliza a neve nas festas de Natal?', ['Pureza', 'Alegria', 'Medo', 'Tristeza'], 0],
            ['Qual país inspirou a figura moderna do Papai Noel?', ['EUA', 'Alemanha', 'Brasil', 'Inglaterra'], 0],
            ['Qual fruta é comum em ceias de Natal tropicais?', ['Uva', 'Abacaxi', 'Banana', 'Melancia'], 0],
            ['Quem mora no Polo Norte?', ['Papai Noel', 'Pinguins', 'Renas', 'Duendes'], 0],
            ['Qual elemento natural enfeita portas no Natal?', ['Guirlanda', 'Rosas', 'Galhos secos', 'Bandeiras'], 0],
            ['Qual bebida é servida na virada do ano?', ['Espumante', 'Cerveja', 'Água', 'Suco'], 0],
            ['Quem são os ajudantes de Papai Noel?', ['Duendes', 'Renas', 'Fadas', 'Bonecos'], 0],
            ['O que representa o sino de Natal?', ['Anúncio da boa nova', 'Alegria', 'Riqueza', 'Paz'], 0],
            ['O que é comum desejar no Ano Novo?', ['Felicidades', 'Tristeza', 'Fome', 'Sono'], 0],
            ['Quantos Reis Magos são citados na tradição?', ['Três', 'Dois', 'Quatro', 'Cinco'], 0],
            ['Qual música tem trenó e sinos?', ['Jingle Bells', 'Noite Feliz', 'Santa Claus', 'Deck the Halls'], 0],
            ['Qual fruta é associada à prosperidade?', ['Uva', 'Maçã', 'Banana', 'Laranja'], 0],
            ['O que se deseja ao dizer “Feliz Natal”?', ['Amor e alegria', 'Comida', 'Viagem', 'Silêncio'], 0],
            ['O que simboliza a estrela no topo da árvore?', ['Guia dos Magos', 'Neve', 'Alegria', 'Luz'], 0],
            ['Quem entrega presentes na noite de Natal?', ['Papai Noel', 'Rena', 'Coelho', 'Rei Mago'], 0],
            ['Qual país tem a tradição de mercados natalinos?', ['Alemanha', 'Brasil', 'Portugal', 'EUA'], 0],
            ['Qual cor é usada para atrair amor no Réveillon?', ['Vermelho', 'Azul', 'Branco', 'Verde'], 0],
            ['O que representa a árvore de Natal?', ['Vida', 'Alegria', 'Festa', 'Paz'], 0],
            ['Qual personagem tem trenó e renas?', ['Papai Noel', 'Duende', 'Rei Mago', 'Boneco'], 0],
            ['Qual é a data do Ano Novo?', ['1º de janeiro', '25 de dezembro', '2 de janeiro', '30 de dezembro'], 0],
            ['O que simboliza a vela natalina?', ['Luz', 'Fogo', 'Paz', 'Amor'], 0],
            ['Qual fruta é símbolo de fartura?', ['Uva', 'Laranja', 'Maçã', 'Banana'], 0],
            ['Qual bebida é mais servida no Réveillon?', ['Espumante', 'Cerveja', 'Suco', 'Água'], 0],
            ['O que simboliza a guirlanda?', ['Boas-vindas', 'Alegria', 'Paz', 'Amor'], 0],
            ['O que representa a cor dourada nas festas de fim de ano?', ['Alegria', 'Esperança', 'Riqueza', 'Paz'], 2],
            ['Qual é o nome da música que fala de trenós e sinos?', ['Noite Feliz', 'Jingle Bells', 'Bate o Sino', 'Santa Claus is Coming'], 1],
            ['Qual doce é tradicional no Natal?', ['Bengala doce', 'Chocolate', 'Pirulito', 'Biscoito'], 0],
            ['Qual país popularizou a figura moderna do Papai Noel?', ['Alemanha', 'EUA', 'Portugal', 'Brasil'], 1],
            ['Qual cor representa amor no Réveillon?', ['Amarelo', 'Verde', 'Vermelho', 'Azul'], 2],
            ['Qual data marca a véspera de Natal?', ['24 de dezembro', '25 de dezembro', '23 de dezembro', '31 de dezembro'], 0],
            ['Quem mora no Polo Norte?', ['Pinguins', 'Renas', 'Papai Noel', 'Coelhos'], 2],
            ['Qual animal puxa o trenó do Papai Noel?', ['Rena', 'Cavalo', 'Burro', 'Urso'], 0],
            ['O que simboliza o fogo na virada do ano?', ['Guerra', 'Luz', 'Purificação', 'Alegria'], 2],
            ['Qual país tem tradição de mercados natalinos ao ar livre?', ['Alemanha', 'Brasil', 'Espanha', 'Canadá'], 0],
            ['Qual fruta representa abundância?', ['Maçã', 'Uva', 'Laranja', 'Abacaxi'], 1],
            ['Quem são os ajudantes do Papai Noel?', ['Duendes', 'Renas', 'Fadas', 'Anjos'], 0],
            ['Qual estação do ano é Natal no hemisfério norte?', ['Primavera', 'Verão', 'Inverno', 'Outono'], 2],
            ['O que é tradicional comer no Réveillon?', ['Sushi', 'Pizza', 'Lentilha', 'Bolo'], 2],
            ['Qual é o nome original da música “Noite Feliz”?', ['Stille Nacht', 'Silent Night', 'Feliz Navidad', 'Holy Night'], 0],
            ['Onde Papai Noel mora?', ['Polo Norte', 'Polo Sul', 'Groenlândia', 'Alasca'], 0],
            ['O que representa a estrela na árvore de Natal?', ['Estrela dos Reis Magos', 'Boa sorte', 'Presente', 'Amor'], 0],
            ['Qual flor vermelha enfeita casas no Natal?', ['Poinsétia', 'Tulipa', 'Margarida', 'Lírio'], 0],
            ['O que as pessoas costumam vestir no Ano Novo para atrair paz?', ['Amarelo', 'Branco', 'Azul', 'Verde'], 1],
            ['Qual música tem o refrão “ho ho ho”?', ['Santa Claus is Coming to Town', 'Deck the Halls', 'Jingle Bells', 'Let it Snow'], 0],
            ['Qual personagem distribui presentes no Natal?', ['Papai Noel', 'Coelhinho da Páscoa', 'Rei Mago', 'Duende'], 0],
            ['Em que país surgiu o panetone?', ['Portugal', 'Itália', 'Espanha', 'França'], 1],
            ['Qual bebida é tradicional na virada de ano?', ['Refrigerante', 'Espumante', 'Cerveja', 'Suco'], 1],
            ['Qual fruta é associada à fartura no Brasil?', ['Abacaxi', 'Uva', 'Laranja', 'Banana'], 1],
            ['Quem costuma deixar presentes nas meias penduradas?', ['Duendes', 'Renas', 'Papai Noel', 'Anjos'], 2],
            ['Qual som é associado ao Natal?', ['Sinos', 'Tambores', 'Violão', 'Aplausos'], 0],
            ['O que se deseja ao dizer “Feliz Natal”?', ['Amor e alegria', 'Tristeza', 'Sono', 'Chuva'], 0],
            ['Qual fruta tropical é comum nas ceias no Brasil?', ['Uva', 'Manga', 'Caju', 'Banana'], 0],
            ['Qual flor é símbolo de Natal?', ['Poinsétia', 'Rosa', 'Lírio', 'Girassol'], 0],
            ['Qual é a cor tradicional da roupa de Papai Noel?', ['Azul', 'Vermelha', 'Verde', 'Dourada'], 1],
            ['Quantas renas puxam o trenó de Papai Noel?', ['Nove', 'Seis', 'Quatro', 'Oito'], 0],
            ['Qual data marca o Ano Novo?', ['25 de dezembro', '31 de dezembro', '1º de janeiro', '2 de janeiro'], 2],
            ['Qual música fala sobre neve e trenós?', ['Jingle Bells', 'Noite Feliz', 'Frosty', 'Bate o Sino'], 0],
            ['Qual fruta é símbolo de prosperidade?', ['Maçã', 'Uva', 'Laranja', 'Abacate'], 1],
            ['O que simboliza a guirlanda na porta?', ['Alegria', 'Boas-vindas', 'Fartura', 'Fé'], 1],
            ['O que simboliza a vela natalina?', ['Luz de Cristo', 'Neve', 'Alegria', 'Festa'], 0],
            ['Qual país é conhecido pelos mercados de Natal?', ['Alemanha', 'EUA', 'Brasil', 'França'], 0],
            ['O que significa “Natal”?', ['Nascimento', 'Paz', 'Alegria', 'Esperança'], 0],
            ['Qual personagem tem barba branca?', ['Papai Noel', 'Rei Mago', 'Coelho', 'Anjo'], 0],
            ['Qual fruta é típica nas festas de fim de ano no Brasil?', ['Uva', 'Banana', 'Caju', 'Pera'], 0],
            ['O que simboliza a árvore de Natal?', ['Festa', 'Vida', 'Alegria', 'Esperança'], 1],
            ['Qual cor atrai dinheiro no Réveillon?', ['Amarelo', 'Branco', 'Vermelho', 'Azul'], 0],
            ['O que se deseja ao dizer “Feliz Ano Novo”?', ['Prosperidade', 'Tristeza', 'Frio', 'Chuva'], 0],
            ['Qual país criou o panetone?', ['Brasil', 'Itália', 'EUA', 'Alemanha'], 1],
            ['Qual fruta representa sorte?', ['Laranja', 'Uva', 'Banana', 'Maçã'], 1],
            ['Quem são os ajudantes do Papai Noel?', ['Renas', 'Duendes', 'Anjos', 'Bonecos'], 1],
            ['Qual canção fala sobre sinos e trenós?', ['Jingle Bells', 'Noite Feliz', 'Frosty', 'Bate o Sino'], 0],
            ['O que simboliza o fogo no Ano Novo?', ['Purificação', 'Alegria', 'Guerra', 'Força'], 0],
            ['Quem visita crianças malcomportadas segundo a lenda?', ['Krampus', 'Rena', 'Duende do bem', 'Fada'], 0],
            ['Qual é a cor da esperança?', ['Verde', 'Branco', 'Amarelo', 'Azul'], 0],
            ['Qual flor vermelha representa o Natal?', ['Poinsétia', 'Lírio', 'Tulipa', 'Margarida'], 0],
            ['Qual bebida é servida no Réveillon?', ['Espumante', 'Refrigerante', 'Suco', 'Água'], 0],
            ['Qual personagem natalino usa trenó?', ['Papai Noel', 'Duende', 'Rena', 'Boneco'], 0],
            ['O que se pendura na lareira para presentes?', ['Meias', 'Fitas', 'Cartas', 'Bolas'], 0],
            ['Onde acontece o Natal com neve?', ['Hemisfério Norte', 'Hemisfério Sul', 'Equador', 'África'], 0],
            ['Qual fruta é comum nas decorações de fim de ano?', ['Uva', 'Banana', 'Abacaxi', 'Pêssego'], 0],
            ['O que significa a estrela de Natal?', ['Estrela dos Reis Magos', 'Neve', 'Amor', 'Paz'], 0],
            ['Quem distribui presentes no Natal?', ['Papai Noel', 'Duendes', 'Coelho', 'Fada'], 0],
            ['Qual cor é usada para atrair paixão?', ['Vermelho', 'Amarelo', 'Azul', 'Verde'], 0],
            ['Quantos Reis Magos visitaram Jesus?', ['Três', 'Quatro', 'Dois', 'Cinco'], 0],
            ['Qual fruta é símbolo de fartura no Brasil?', ['Uva', 'Abacaxi', 'Laranja', 'Banana'], 0],
            ['Qual flor representa Natal?', ['Poinsétia', 'Orquídea', 'Rosa', 'Lírio'], 0],
            ['O que simboliza a neve?', ['Pureza', 'Frio', 'Medo', 'Esperança'], 0],
            ['Qual personagem lendário tem gorro vermelho?', ['Papai Noel', 'Krampus', 'Duende', 'Boneco de Neve'], 0],
            ['O que significa a palavra “Réveillon”?', ['Recomeço', 'Alegria', 'Festa', 'Presente'], 0],
            ['Qual país tem mercados de Natal famosos?', ['Alemanha', 'Brasil', 'Portugal', 'EUA'], 0],
            ['O que se come para atrair prosperidade?', ['Lentilha', 'Pizza', 'Bolo', 'Sopa'], 0],
            ['O que se deseja ao brindar na virada do ano?', ['Felicidades', 'Sono', 'Chuva', 'Silêncio'], 0],
            ['Qual música fala de Papai Noel?', ['Santa Claus is Coming to Town', 'Frosty', 'Deck the Halls', 'Noite Feliz'], 0],
            ['Qual é a bebida mais servida no Ano Novo?', ['Espumante', 'Água', 'Suco', 'Refrigerante'], 0],
            ['Qual fruta simboliza prosperidade?', ['Uva', 'Banana', 'Manga', 'Pera'], 0],
            ['Quem são os ajudantes do Papai Noel?', ['Duendes', 'Fadas', 'Renas', 'Anjos'], 0],
            ['Onde Papai Noel mora?', ['Polo Norte', 'Polo Sul', 'Brasil', 'EUA'], 0],
            ['O que representa a estrela natalina?', ['Estrela dos Magos', 'Fogo', 'Esperança', 'Festa'], 0],
            ['Qual flor enfeita mesas de Natal?', ['Poinsétia', 'Margarida', 'Girassol', 'Lírio'], 0],
            ['Qual cor representa paz no Ano Novo?', ['Branco', 'Vermelho', 'Amarelo', 'Azul'], 0],
            ['O que significa “Natal”?', ['Nascimento', 'Paz', 'Festa', 'Esperança'], 0],
            ['Qual música natalina é mais famosa?', ['Jingle Bells', 'Noite Feliz', 'Bate o Sino', 'Deck the Halls'], 0],
            ['Qual fruta tropical aparece nas ceias?', ['Uva', 'Abacaxi', 'Manga', 'Banana'], 0],
            ['Qual personagem lendário entrega presentes?', ['Papai Noel', 'Duendes', 'Rei Mago', 'Boneco'], 0],
            ['Qual bebida está presente no Réveillon?', ['Espumante', 'Suco', 'Refrigerante', 'Chá'], 0],
            ['Quem são os ajudantes de Papai Noel?', ['Duendes', 'Renas', 'Fadas', 'Bonecos'], 0],
            ['Qual fruta representa prosperidade?', ['Uva', 'Laranja', 'Maçã', 'Banana'], 0],
            ['O que representa a árvore de Natal?', ['Vida', 'Alegria', 'Esperança', 'Festa'], 0],
            ['O que significa “Merry Christmas”?', ['Feliz Natal', 'Bom Ano', 'Boas Festas', 'Feliz Ano Novo'], 0],
            ['Qual personagem tem trenó e renas?', ['Papai Noel', 'Duende', 'Boneco de Neve', 'Rei Mago'], 0],
            ['Qual flor vermelha é símbolo de Natal?', ['Poinsétia', 'Lírio', 'Tulipa', 'Orquídea'], 0],
            ['Qual som é mais associado ao Natal?', ['Sinos', 'Gaita', 'Gongo', 'Tambor'], 0],
            ['O que se deseja no brinde do Ano Novo?', ['Felicidade', 'Tristeza', 'Silêncio', 'Sono'], 0],
            ['Qual fruta é mais usada nas festas tropicais?', ['Uva', 'Abacaxi', 'Manga', 'Pera'], 0],
            ['Qual país é famoso por mercados natalinos?', ['Alemanha', 'Portugal', 'EUA', 'França'], 0],
            ['O que significa o sino de Natal?', ['Anúncio da boa nova', 'Paz', 'Alegria', 'Esperança'], 0],
            ['Qual personagem tem barba branca e gorro vermelho?', ['Papai Noel', 'Krampus', 'Boneco', 'Rena'], 0],
            ['Qual é o símbolo que representa luz no Natal?', ['Estrela', 'Guirlanda', 'Meia', 'Presépio'], 0],
            ['Qual fruta é associada à fartura nas festas de fim de ano?', ['Laranja', 'Uva', 'Maçã', 'Banana'], 1],
            ['Qual a cor que simboliza esperança no Ano Novo?', ['Azul', 'Verde', 'Branco', 'Vermelho'], 1],
            ['Qual país tem mercados natalinos famosos?', ['Alemanha', 'Portugal', 'EUA', 'Brasil'], 0],
            ['O que significa a estrela de Natal?', ['Estrela dos Reis Magos', 'Neve', 'Amor', 'Alegria'], 0],
            ['Qual bebida é tradicional na virada de ano?', ['Cerveja', 'Espumante', 'Refrigerante', 'Suco'], 1],
            ['Quem mora no Polo Norte segundo a lenda?', ['Renas', 'Papai Noel', 'Coelhos', 'Fadas'], 1],
            ['Qual flor vermelha é símbolo de Natal?', ['Poinsétia', 'Girassol', 'Rosa', 'Margarida'], 0],
            ['Qual cor representa paz no Réveillon?', ['Amarelo', 'Branco', 'Azul', 'Vermelho'], 1],
            ['Qual personagem natalino tem barba branca?', ['Papai Noel', 'Duende', 'Boneco de Neve', 'Krampus'], 0],
            ['O que simboliza o fogo nas festas de virada de ano?', ['Purificação', 'Calor', 'Alegria', 'Sol'], 0],
            ['O que se deseja ao dizer “Feliz Ano Novo”?', ['Tristeza', 'Prosperidade', 'Sono', 'Férias'], 1],
            ['Qual personagem entrega presentes no Natal?', ['Rei Mago', 'Papai Noel', 'Rena', 'Duende'], 1],
            ['Onde tradicionalmente as pessoas pulam ondas?', ['Praia', 'Rua', 'Igreja', 'Montanha'], 0],
            ['Qual cor atrai amor no Ano Novo?', ['Amarelo', 'Vermelho', 'Verde', 'Azul'], 1],
            ['Qual fruta é usada como símbolo de prosperidade?', ['Maçã', 'Uva', 'Laranja', 'Banana'], 1],
            ['Qual som é típico das festas de Natal?', ['Sinos', 'Tambor', 'Violão', 'Gongo'], 0],
            ['Qual é a data do Ano Novo?', ['1º de janeiro', '31 de dezembro', '25 de dezembro', '30 de dezembro'], 0],
            ['Qual país inspirou o Papai Noel moderno?', ['Brasil', 'EUA', 'Alemanha', 'França'], 1],
            ['Quantos Reis Magos visitaram Jesus?', ['Três', 'Dois', 'Quatro', 'Cinco'], 0],
            ['Qual flor vermelha enfeita mesas natalinas?', ['Poinsétia', 'Tulipa', 'Girassol', 'Lírio'], 0],
            ['Qual fruta tropical está presente nas ceias no Brasil?', ['Uva', 'Banana', 'Manga', 'Caju'], 0],
            ['Quem são os ajudantes de Papai Noel?', ['Renas', 'Duendes', 'Anjos', 'Estrelas'], 1],
            ['O que simboliza a guirlanda na porta?', ['Boas-vindas', 'Alegria', 'Paz', 'Esperança'], 0],
            ['Qual cor representa riqueza no Réveillon?', ['Verde', 'Branco', 'Amarelo', 'Vermelho'], 2],
            ['Qual música natalina fala de sinos?', ['Jingle Bells', 'Noite Feliz', 'Frosty', 'Deck the Halls'], 0],
            ['O que significa “Natal”?', ['Nascimento', 'Alegria', 'Presente', 'Luz'], 0],
            ['Quem tem trenó puxado por renas?', ['Papai Noel', 'Rei Mago', 'Duende', 'Boneco de Neve'], 0],
            ['Qual fruta representa fartura no Brasil?', ['Uva', 'Pêssego', 'Laranja', 'Banana'], 0],
            ['Onde é celebrado Natal com neve?', ['Hemisfério Norte', 'Brasil', 'Equador', 'África'], 0],
            ['Qual bebida é mais consumida na virada?', ['Espumante', 'Cerveja', 'Suco', 'Água'], 0],
            ['Qual flor representa o Natal?', ['Poinsétia', 'Lírio', 'Tulipa', 'Orquídea'], 0],
            ['O que simboliza a estrela de Natal?', ['Estrela dos Reis Magos', 'Alegria', 'Neve', 'Festa'], 0],
            ['Qual fruta costuma estar na mesa de Ano Novo?', ['Uva', 'Banana', 'Caju', 'Maçã'], 0],
            ['Qual personagem diz “Ho Ho Ho”?', ['Papai Noel', 'Duende', 'Krampus', 'Rei Mago'], 0],
            ['Quem ajuda Papai Noel a fabricar brinquedos?', ['Renas', 'Duendes', 'Anjos', 'Bonecos'], 1],
            ['O que significa a estrela no topo da árvore?', ['Luz que guiou os Magos', 'Paz', 'Alegria', 'Natal'], 0],
            ['Qual cor atrai paz?', ['Amarelo', 'Branco', 'Vermelho', 'Verde'], 1],
            ['Qual fruta é símbolo de prosperidade?', ['Uva', 'Banana', 'Laranja', 'Manga'], 0],
            ['Quem mora no Polo Norte?', ['Papai Noel', 'Renas', 'Fadas', 'Duendes'], 0],
            ['O que se deseja no brinde do Ano Novo?', ['Felicidade', 'Tristeza', 'Frio', 'Sono'], 0],
            ['Qual país criou o panetone?', ['EUA', 'Itália', 'Alemanha', 'Brasil'], 1],
            ['Qual flor representa o Natal?', ['Poinsétia', 'Girassol', 'Rosa', 'Tulipa'], 0],
            ['Qual fruta representa sorte e fartura?', ['Uva', 'Maçã', 'Banana', 'Abacaxi'], 0],
            ['Qual personagem lendário tem gorro vermelho?', ['Papai Noel', 'Duende', 'Krampus', 'Boneco'], 0],
            ['O que simboliza o fogo na virada do ano?', ['Purificação', 'Alegria', 'Força', 'Tristeza'], 0],
            ['Qual bebida é símbolo do Ano Novo?', ['Espumante', 'Água', 'Suco', 'Cerveja'], 0],
            ['Qual fruta tropical aparece nas ceias?', ['Uva', 'Manga', 'Caju', 'Laranja'], 0],
            ['Qual país tem a tradição de mercados de Natal?', ['Alemanha', 'Brasil', 'Portugal', 'Espanha'], 0],
            ['Qual personagem tem barba branca?', ['Papai Noel', 'Duende', 'Anjo', 'Boneco'], 0],
            ['Qual é a data do Natal?', ['25 de dezembro', '31 de dezembro', '1º de janeiro', '24 de dezembro'], 0],
            ['Quem entrega presentes às crianças?', ['Papai Noel', 'Rei Mago', 'Duende', 'Boneco'], 0],
            ['Qual cor atrai amor?', ['Vermelho', 'Azul', 'Verde', 'Branco'], 0],
            ['Quem são os ajudantes de Papai Noel?', ['Duendes', 'Renas', 'Fadas', 'Bonecos'], 0],
            ['Qual flor é símbolo natalino?', ['Poinsétia', 'Rosa', 'Tulipa', 'Lírio'], 0],
            ['Qual fruta é símbolo de prosperidade?', ['Uva', 'Banana', 'Pêssego', 'Laranja'], 0],
            ['Qual personagem lendário usa trenó?', ['Papai Noel', 'Duende', 'Boneco', 'Krampus'], 0],
            ['O que simboliza o sino natalino?', ['Anúncio da boa nova', 'Festa', 'Amor', 'Riqueza'], 0],
            ['Qual música natalina é mais famosa?', ['Jingle Bells', 'Noite Feliz', 'Bate o Sino', 'Santa Claus'], 0],
            ['Qual flor vermelha é tradicional?', ['Poinsétia', 'Lírio', 'Rosa', 'Tulipa'], 0],
            ['Qual fruta representa fartura?', ['Uva', 'Maçã', 'Banana', 'Caju'], 0],
            ['Qual personagem diz “Ho Ho Ho”?', ['Papai Noel', 'Duende', 'Boneco', 'Rena'], 0],
            ['O que simboliza a guirlanda?', ['Boas-vindas', 'Alegria', 'Amor', 'Festa'], 0],
            ['Qual país originou o Papai Noel moderno?', ['EUA', 'Brasil', 'Alemanha', 'Portugal'], 0],
            ['Qual fruta tropical é usada no Natal brasileiro?', ['Uva', 'Abacaxi', 'Banana', 'Manga'], 0],
            ['Qual bebida é típica na virada?', ['Espumante', 'Refrigerante', 'Suco', 'Chá'], 0],
            ['Quem fabrica os brinquedos do Papai Noel?', ['Duendes', 'Renas', 'Anjos', 'Bonecos'], 0],
            ['Qual é a fruta símbolo do Ano Novo?', ['Uva', 'Laranja', 'Maçã', 'Banana'], 0],
            ['Qual flor é associada ao Natal?', ['Poinsétia', 'Orquídea', 'Rosa', 'Tulipa'], 0],
            ['O que simboliza o fogo de artifício na virada?', ['Renovação', 'Festa', 'Alegria', 'Luz'], 0],
            ['Onde Papai Noel mora?', ['Polo Norte', 'EUA', 'Brasil', 'Alemanha'], 0],
            ['Qual música tem sinos e trenós?', ['Jingle Bells', 'Bate o Sino', 'Frosty', 'Noite Feliz'], 0],
            ['Qual flor é símbolo natalino?', ['Poinsétia', 'Rosa', 'Lírio', 'Orquídea'], 0],
            ['Qual fruta representa abundância?', ['Uva', 'Banana', 'Laranja', 'Manga'], 0],
            ['Qual personagem lendário tem renas?', ['Papai Noel', 'Krampus', 'Duende', 'Boneco'], 0],
            ['O que significa “Merry Christmas”?', ['Feliz Natal', 'Bom Ano', 'Boas Festas', 'Feliz Ano Novo'], 0],
            ['Qual bebida é símbolo da virada de ano?', ['Espumante', 'Água', 'Refrigerante', 'Cerveja'], 0],
            ['Qual fruta tropical enfeita mesas brasileiras?', ['Uva', 'Abacaxi', 'Banana', 'Laranja'], 0],
            ['Qual país tem mercados de Natal tradicionais?', ['Alemanha', 'Portugal', 'Espanha', 'Brasil'], 0],
            ['Quem distribui presentes na noite de Natal?', ['Papai Noel', 'Duende', 'Rei Mago', 'Boneco'], 0],
            ['Qual cor representa paz no Réveillon?', ['Branco', 'Verde', 'Vermelho', 'Amarelo'], 0],
            ['Qual flor vermelha é usada nas festas?', ['Poinsétia', 'Rosa', 'Girassol', 'Lírio'], 0],
            ['Qual fruta simboliza prosperidade?', ['Uva', 'Laranja', 'Banana', 'Manga'], 0],
            ['Quem são os ajudantes de Papai Noel?', ['Duendes', 'Renas', 'Bonecos', 'Fadas'], 0],
            ['Qual música fala sobre trenó?', ['Jingle Bells', 'Noite Feliz', 'Deck the Halls', 'Frosty'], 0],
            ['O que simboliza a estrela natalina?', ['Luz dos Magos', 'Alegria', 'Amor', 'Festa'], 0],
            ['Qual país é conhecido pelos mercados natalinos?', ['Alemanha', 'Brasil', 'Portugal', 'Espanha'], 0],
            ['Qual personagem tem barba branca?', ['Papai Noel', 'Boneco', 'Duende', 'Rena'], 0],
            ['Qual fruta tropical é comum no Natal?', ['Uva', 'Manga', 'Caju', 'Banana'], 0],
            ['O que simboliza o sino de Natal?', ['Anúncio da boa nova', 'Amor', 'Alegria', 'Paz'], 0],
            ['Qual personagem usa um trenó puxado por renas?', ['Papai Noel', 'Coelho', 'Rei Mago', 'Anjo'], 0],
            ['Qual flor é tradicional nas decorações natalinas?', ['Girassol', 'Poinsétia', 'Margarida', 'Rosa'], 1],
            ['O que simboliza a estrela no topo da árvore de Natal?', ['Esperança', 'Estrela dos Magos', 'Alegria', 'Fartura'], 1],
            ['Qual fruta é associada à fartura no Ano Novo?', ['Uva', 'Banana', 'Abacaxi', 'Manga'], 0],
            ['Qual país é famoso pelos mercados de Natal?', ['Brasil', 'Alemanha', 'EUA', 'Portugal'], 1],
            ['Qual bebida simboliza a virada do ano?', ['Cerveja', 'Suco', 'Espumante', 'Chá'], 2],
            ['Qual cor representa paz no Réveillon?', ['Amarelo', 'Branco', 'Vermelho', 'Azul'], 1],
            ['Quem ajuda o Papai Noel na oficina?', ['Duendes', 'Renas', 'Bonecos de Neve', 'Reis Magos'], 0],
            ['Qual cor atrai amor na virada do ano?', ['Vermelho', 'Verde', 'Amarelo', 'Azul'], 0],
            ['Qual flor vermelha é símbolo do Natal?', ['Rosa', 'Poinsétia', 'Lírio', 'Tulipa'], 1],
            ['Qual fruta é usada como símbolo de prosperidade?', ['Laranja', 'Uva', 'Pera', 'Maçã'], 1],
            ['Quem mora no Polo Norte segundo a tradição?', ['Renas', 'Papai Noel', 'Coelhos', 'Elfos'], 1],
            ['O que significa “Natal”?', ['Alegria', 'Nascimento', 'Paz', 'Festa'], 1],
            ['Qual música natalina é mais famosa no mundo?', ['Noite Feliz', 'Jingle Bells', 'Bate o Sino', 'Deck the Halls'], 1],
            ['Qual som é mais associado ao Natal?', ['Sinos', 'Tambor', 'Gongo', 'Violão'], 0],
            ['Quem visita crianças na noite de Natal?', ['Coelho da Páscoa', 'Papai Noel', 'Rena', 'Anjo'], 1],
            ['Onde é comum celebrar o Ano Novo no Brasil?', ['Praia', 'Igreja', 'Montanha', 'Rua'], 0],
            ['Qual flor vermelha representa o Natal?', ['Poinsétia', 'Girassol', 'Rosa', 'Orquídea'], 0],
            ['Qual bebida é tradicional na virada do ano?', ['Suco', 'Espumante', 'Água', 'Cerveja'], 1],
            ['Quem são os ajudantes de Papai Noel?', ['Duendes', 'Renas', 'Anjos', 'Fadas'], 0],
            ['O que representa a estrela natalina?', ['Alegria', 'Estrela dos Magos', 'Luz', 'Esperança'], 1],
            ['Qual fruta tropical aparece nas ceias de fim de ano?', ['Uva', 'Banana', 'Manga', 'Abacaxi'], 0],
            ['O que simboliza o sino de Natal?', ['Anúncio da boa nova', 'Alegria', 'Amor', 'Festa'], 0],
            ['Qual país popularizou a imagem moderna do Papai Noel?', ['Alemanha', 'EUA', 'Portugal', 'Brasil'], 1],
            ['Qual é a data do Ano Novo?', ['1º de janeiro', '31 de dezembro', '25 de dezembro', '2 de janeiro'], 0],
            ['Qual personagem diz “Ho Ho Ho”?', ['Papai Noel', 'Duende', 'Rena', 'Anjo'], 0],
            ['Qual fruta representa prosperidade no Réveillon?', ['Uva', 'Banana', 'Pêssego', 'Laranja'], 0],
            ['Quem entrega presentes no Natal?', ['Rena', 'Papai Noel', 'Rei Mago', 'Coelho'], 1],
            ['Qual flor é símbolo natalino?', ['Lírio', 'Poinsétia', 'Rosa', 'Margarida'], 1],
            ['Qual cor atrai dinheiro no Réveillon?', ['Amarelo', 'Branco', 'Vermelho', 'Azul'], 0],
            ['Qual música fala de trenós e sinos?', ['Jingle Bells', 'Noite Feliz', 'Bate o Sino', 'Frosty'], 0],
            ['Qual bebida é símbolo do brinde de Ano Novo?', ['Espumante', 'Água', 'Suco', 'Cerveja'], 0],
            ['Qual fruta tropical enfeita as mesas brasileiras?', ['Uva', 'Manga', 'Banana', 'Laranja'], 0],
            ['Quem são os ajudantes de Papai Noel?', ['Duendes', 'Anjos', 'Renas', 'Bonecos'], 0],
            ['O que representa a árvore de Natal?', ['Vida', 'Alegria', 'Esperança', 'Amor'], 0],
            ['Qual flor vermelha é usada no Natal?', ['Poinsétia', 'Lírio', 'Tulipa', 'Rosa'], 0],
            ['Qual fruta representa fartura?', ['Uva', 'Banana', 'Abacaxi', 'Manga'], 0],
            ['Quem mora no Polo Norte?', ['Papai Noel', 'Duendes', 'Renas', 'Fadas'], 0],
            ['O que significa “Feliz Natal”?', ['Alegria', 'Amor e paz', 'Boa noite', 'Bom Ano'], 1],
            ['Qual país tem mercados natalinos tradicionais?', ['Alemanha', 'Portugal', 'EUA', 'Brasil'], 0],
            ['Quem entrega presentes às crianças?', ['Papai Noel', 'Coelho', 'Anjo', 'Rena'], 0],
            ['Qual fruta representa prosperidade?', ['Uva', 'Laranja', 'Banana', 'Pêssego'], 0],
            ['O que simboliza a estrela de Natal?', ['Estrela dos Reis Magos', 'Alegria', 'Amor', 'Felicidade'], 0],
            ['Qual personagem tem barba branca?', ['Papai Noel', 'Krampus', 'Duende', 'Boneco'], 0],
            ['Qual bebida é mais servida na virada?', ['Espumante', 'Suco', 'Refrigerante', 'Cerveja'], 0],
            ['Qual flor vermelha enfeita mesas de Natal?', ['Poinsétia', 'Rosa', 'Lírio', 'Orquídea'], 0],
            ['Quem são os ajudantes do Papai Noel?', ['Duendes', 'Renas', 'Fadas', 'Bonecos'], 0],
            ['Qual fruta tropical é comum no Natal brasileiro?', ['Uva', 'Banana', 'Manga', 'Abacaxi'], 0],
            ['O que simboliza o sino natalino?', ['Anúncio da boa nova', 'Alegria', 'Amor', 'Festa'], 0],
            ['Qual país criou o panetone?', ['Itália', 'EUA', 'Alemanha', 'Brasil'], 0],
            ['Qual flor é símbolo de Natal?', ['Poinsétia', 'Tulipa', 'Girassol', 'Lírio'], 0],
            ['Qual fruta representa fartura no Ano Novo?', ['Uva', 'Maçã', 'Banana', 'Pêssego'], 0],
            ['Quem mora no Polo Norte?', ['Papai Noel', 'Krampus', 'Renas', 'Bonecos'], 0],
            ['O que significa “Réveillon”?', ['Recomeço', 'Alegria', 'Luz', 'Festa'], 0],
            ['Qual música natalina fala de sinos?', ['Jingle Bells', 'Deck the Halls', 'Frosty', 'Noite Feliz'], 0],
            ['Qual personagem tem gorro vermelho?', ['Papai Noel', 'Duende', 'Rena', 'Krampus'], 0],
            ['O que simboliza a árvore de Natal?', ['Vida', 'Amor', 'Fé', 'Alegria'], 0],
            ['Qual fruta é símbolo de fartura?', ['Uva', 'Maçã', 'Banana', 'Manga'], 0],
            ['Qual flor representa o Natal?', ['Poinsétia', 'Tulipa', 'Rosa', 'Orquídea'], 0],
            ['Quem ajuda Papai Noel?', ['Duendes', 'Renas', 'Bonecos', 'Anjos'], 0],
            ['Qual som é típico das festas natalinas?', ['Sinos', 'Tambor', 'Gongo', 'Flauta'], 0],
            ['Qual fruta tropical aparece nas ceias?', ['Uva', 'Laranja', 'Manga', 'Banana'], 0],
            ['Qual personagem lendário tem trenó?', ['Papai Noel', 'Rena', 'Duende', 'Boneco'], 0],
            ['O que significa “Merry Christmas”?', ['Feliz Natal', 'Bom Ano', 'Boas Festas', 'Feliz Ano Novo'], 0],
            ['Qual bebida é símbolo do Réveillon?', ['Espumante', 'Suco', 'Refrigerante', 'Chá'], 0],
            ['Qual fruta tropical enfeita mesas?', ['Uva', 'Abacaxi', 'Banana', 'Manga'], 0],
            ['Quem entrega presentes no Natal?', ['Papai Noel', 'Rena', 'Rei Mago', 'Duende'], 0],
            ['Qual cor representa paz?', ['Branco', 'Vermelho', 'Amarelo', 'Verde'], 0],
            ['Qual flor vermelha é tradicional no Natal?', ['Poinsétia', 'Tulipa', 'Rosa', 'Lírio'], 0],
            ['Qual fruta representa prosperidade?', ['Uva', 'Laranja', 'Banana', 'Manga'], 0],
            ['Quem são os ajudantes de Papai Noel?', ['Duendes', 'Renas', 'Bonecos', 'Fadas'], 0],
            ['Qual música natalina é mais conhecida?', ['Jingle Bells', 'Deck the Halls', 'Noite Feliz', 'Frosty'], 0],
            ['O que simboliza a estrela natalina?', ['Estrela dos Magos', 'Alegria', 'Amor', 'Esperança'], 0],
            ['Qual país tem mercados de Natal?', ['Alemanha', 'Portugal', 'Espanha', 'Brasil'], 0],
            ['Qual personagem tem barba branca?', ['Papai Noel', 'Krampus', 'Boneco', 'Duende'], 0],
            ['Qual fruta tropical é comum nas festas?', ['Uva', 'Manga', 'Banana', 'Laranja'], 0],
            ['O que simboliza o sino natalino?', ['Anúncio da boa nova', 'Alegria', 'Festa', 'Amor'], 0],
            ['Qual flor vermelha representa o Natal?', ['Poinsétia', 'Girassol', 'Rosa', 'Margarida'], 0],
            ['Qual bebida é tradicional na virada?', ['Espumante', 'Cerveja', 'Suco', 'Água'], 0],
            ['Quem ajuda Papai Noel a fazer brinquedos?', ['Duendes', 'Renas', 'Anjos', 'Bonecos'], 0],
            ['Qual fruta tropical representa fartura?', ['Uva', 'Banana', 'Manga', 'Pêssego'], 0],
            ['Qual música fala de trenó?', ['Jingle Bells', 'Noite Feliz', 'Frosty', 'Deck the Halls'], 0],
            ['Qual personagem tem gorro vermelho?', ['Papai Noel', 'Rena', 'Duende', 'Boneco'], 0],
            ['O que simboliza a árvore de Natal?', ['Vida', 'Amor', 'Festa', 'Alegria'], 0],
            ['Qual flor representa Natal?', ['Poinsétia', 'Rosa', 'Tulipa', 'Lírio'], 0],
            ['Quem entrega presentes?', ['Papai Noel', 'Rena', 'Duende', 'Rei Mago'], 0],
            ['Qual fruta representa prosperidade?', ['Uva', 'Banana', 'Pêssego', 'Laranja'], 0],
            ['Qual país tem mercados de Natal famosos?', ['Alemanha', 'Espanha', 'Brasil', 'França'], 0],
            ['Qual personagem lendário diz “Ho Ho Ho”?', ['Papai Noel', 'Krampus', 'Duende', 'Rena'], 0],
            ['Onde nasceu Jesus segundo a tradição cristã?', ['Belém', 'Jerusalém', 'Roma', 'Nazaré'], 0],
            ['Qual foi o presente levado por Baltazar ao Menino Jesus?', ['Mirra', 'Ouro', 'Incenso', 'Prata'], 0],
            ['Qual foi o presente levado por Gaspar ao Menino Jesus?', ['Incenso', 'Ouro', 'Mirra', 'Perfume'], 0],
            ['Qual foi o presente levado por Melchior ao Menino Jesus?', ['Ouro', 'Incenso', 'Prata', 'Mirra'], 0],
            ['Quantos Evangelhos canônicos falam sobre o nascimento de Jesus?', ['Dois', 'Um', 'Quatro', 'Três'], 0],
            ['Quem anunciou aos pastores o nascimento de Jesus?', ['Anjos', 'Reis Magos', 'Papai Noel', 'Duendes'], 0],
            ['Qual é o nome do local onde Jesus nasceu?', ['Manjedoura', 'Estábulo', 'Igreja', 'Templo'], 0],
            ['Quem foi a mãe de Jesus?', ['Maria', 'Isabel', 'Ana', 'Eva'], 0],
            ['Quem foi o pai terreno de Jesus?', ['José', 'Pedro', 'Tiago', 'João'], 0],
            ['Em que cidade Jesus cresceu?', ['Nazaré', 'Belém', 'Jerusalém', 'Roma'], 0],
            ['O que significa a palavra “Emmanuel”?', ['Deus conosco', 'Luz divina', 'Presente de Deus', 'Salvador'], 0],
            ['Qual símbolo representa a luz de Cristo no Natal?', ['Vela', 'Presépio', 'Guirlanda', 'Meia'], 0],
            ['Quem foi o imperador romano no nascimento de Jesus?', ['César Augusto', 'Nero', 'Cláudio', 'Constantino'], 0],
            ['Por qual motivo Maria e José estavam em Belém?', ['Censo', 'Festa', 'Casamento', 'Comércio'], 0],
            ['Quem anunciou a gravidez de Maria?', ['Anjo Gabriel', 'Anjo Rafael', 'Pedro', 'João'], 0],
            ['Qual foi o sinal celestial do nascimento de Jesus?', ['Estrela', 'Lua cheia', 'Cometa', 'Aurora'], 0],
            ['Em que data é comemorado o nascimento de Jesus?', ['25 de dezembro', '24 de dezembro', '31 de dezembro', '1º de janeiro'], 0],
            ['Qual animal é tradicionalmente mostrado ao lado da manjedoura?', ['Boi e jumento', 'Rena e cavalo', 'Cachorro e gato', 'Leão e cordeiro'], 0],
            ['Quem perseguiu Jesus após seu nascimento?', ['Herodes', 'Pilatos', 'César', 'Judas'], 0],
            ['Qual o nome do hino “Noite Feliz” em alemão?', ['Stille Nacht', 'O Tannenbaum', 'O Heilige Nacht', 'Heilige'], 0],
            ['Em qual país foi composta a música “Noite Feliz”?', ['Áustria', 'Alemanha', 'Suíça', 'Itália'], 0],
            ['Quem compôs “Noite Feliz”?', ['Franz Xaver Gruber', 'Beethoven', 'Mozart', 'Bach'], 0],
            ['Em que ano foi composta “Noite Feliz”?', ['1818', '1900', '1799', '1875'], 0],
            ['Qual é a tradução literal de “Stille Nacht”?', ['Noite Silenciosa', 'Noite Santa', 'Feliz Natal', 'Noite de Paz'], 0],
            ['Qual país deu origem ao presépio?', ['Itália', 'Alemanha', 'Espanha', 'França'], 0],
            ['Quem criou o primeiro presépio?', ['São Francisco de Assis', 'São Pedro', 'São João', 'Santo Agostinho'], 0],
            ['Em que século surgiu o presépio?', ['XIII', 'XV', 'X', 'IX'], 0],
            ['Qual foi o primeiro país a adotar a árvore de Natal?', ['Alemanha', 'Inglaterra', 'França', 'Itália'], 0],
            ['De qual planta se originou a tradição da árvore de Natal?', ['Pinheiro', 'Cedro', 'Carvalho', 'Eucalipto'], 0],
            ['Qual personagem histórico inspirou o Papai Noel?', ['São Nicolau', 'São João', 'São Pedro', 'Santo Antônio'], 0],
            ['Em qual país nasceu São Nicolau?', ['Turquia', 'Alemanha', 'Espanha', 'França'], 0],
            ['Qual empresa ajudou a popularizar a imagem moderna do Papai Noel?', ['Coca-Cola', 'Disney', 'Nestlé', 'Sony'], 0],
            ['Em qual década a Coca-Cola popularizou a imagem do bom velhinho?', ['1930', '1950', '1920', '1940'], 0],
            ['Qual cor predominava nas roupas de São Nicolau?', ['Vermelho', 'Azul', 'Verde', 'Branco'], 2],
            ['Qual data é conhecida como “Noite Santa”?', ['24 de dezembro', '25 de dezembro', '1º de janeiro', '31 de dezembro'], 0],
            ['Quem costuma receber presentes em meias penduradas?', ['Crianças', 'Animais', 'Vizinhos', 'Reis Magos'], 0],
            ['Em que país surgiu a tradição das meias de Natal?', ['Holanda', 'Alemanha', 'EUA', 'Itália'], 0],
            ['Quantos dias duram as comemorações do Advento?', ['Quatro semanas', 'Três semanas', 'Uma semana', 'Cinco semanas'], 0],
            ['Qual é a cor tradicional da vela do Advento?', ['Roxa', 'Vermelha', 'Branca', 'Azul'], 0],
            ['Quantas velas compõem a Coroa do Advento?', ['Quatro', 'Três', 'Cinco', 'Seis'], 0],
            ['Qual é o significado da Coroa do Advento?', ['Preparação para o Natal', 'Nascimento de Jesus', 'Fé', 'Alegria'], 0],
            ['Qual país tem o maior mercado de Natal do mundo?', ['Alemanha', 'EUA', 'França', 'Áustria'], 0],
            ['Qual é o nome em inglês do presépio?', ['Nativity Scene', 'Christmas Scene', 'Holy Scene', 'Stable Show'], 0],
            ['Em que país surgiu a tradição dos cartões de Natal?', ['Inglaterra', 'Alemanha', 'França', 'EUA'], 0],
            ['Em qual século surgiram os cartões de Natal?', ['XIX', 'XVIII', 'XX', 'XV'], 0],
            ['Quem é conhecido como “o bom velhinho”?', ['Papai Noel', 'Jesus', 'São Nicolau', 'Rudolph'], 0],
            ['Qual animal puxa o trenó do Papai Noel?', ['Rena', 'Cavalo', 'Boi', 'Jumento'], 0],
            ['Quantas renas puxam o trenó de Papai Noel tradicionalmente?', ['Nove', 'Oito', 'Seis', 'Dez'], 0],
            ['Qual é o nome da rena com nariz vermelho?', ['Rudolph', 'Dasher', 'Blitzen', 'Comet'], 0],
            ['Onde Papai Noel mora?', ['Polo Norte', 'Groenlândia', 'Alemanha', 'Alasca'], 0],
            ['Qual é o nome da esposa do Papai Noel?', ['Mamãe Noel', 'Maria Noel', 'Mrs. North', 'Sra. Rudolph'], 0],
            ['Como se chama o trenó do Papai Noel?', ['Sleigh', 'SantaCar', 'ReindeerExpress', 'MagicFly'], 0],
            ['Quem ajuda Papai Noel na oficina?', ['Duendes', 'Elfos negros', 'Bonecos de neve', 'Coelhos'], 0],
            ['O que representa a estrela de Belém?', ['O nascimento de Jesus', 'A chegada do inverno', 'A festa dos reis', 'A luz do ano novo'], 0],
            ['Qual dia comemora-se o Dia de Reis?', ['6 de janeiro', '1º de janeiro', '5 de janeiro', '7 de janeiro'], 0],
            ['Qual nome é dado ao período entre o Natal e o Dia de Reis?', ['Epifania', 'Advento', 'Pentecostes', 'Páscoa'], 0],
            ['O que significa Epifania?', ['Manifestação de Deus', 'Chegada do inverno', 'Renascimento', 'Alegria eterna'], 0],
            ['Quantos reis magos visitaram Jesus?', ['Três', 'Quatro', 'Dois', 'Cinco'], 0],
            ['Como se chamam os três reis magos?', ['Baltazar, Melchior e Gaspar', 'Pedro, João e Tiago', 'Rudolph, Dasher e Donner', 'Lucas, Marcos e Mateus'], 0],
            ['Qual presente representa a realeza de Jesus?', ['Ouro', 'Incenso', 'Mirra', 'Paz'], 0],
            ['Qual presente representa a divindade de Jesus?', ['Incenso', 'Ouro', 'Mirra', 'Luz'], 0],
            ['Qual presente representa o sacrifício de Jesus?', ['Mirra', 'Ouro', 'Incenso', 'Esperança'], 0],
            ['Qual país comemora o Natal no verão?', ['Brasil', 'Alemanha', 'Rússia', 'Canadá'], 0],
            ['O que representa a vela de Natal?', ['Luz de Cristo', 'Alegria', 'Festa', 'Neve'], 0],
            ['O que simboliza a guirlanda?', ['Boas-vindas e eternidade', 'Fartura', 'Fé', 'Paz'], 0],
            ['Qual flor é símbolo natalino?', ['Poinsétia', 'Girassol', 'Rosa', 'Tulipa'], 0],
            ['Qual cor simboliza prosperidade no Réveillon?', ['Amarelo', 'Branco', 'Vermelho', 'Verde'], 0],
            ['Qual cor simboliza amor no Réveillon?', ['Vermelho', 'Azul', 'Amarelo', 'Branco'], 0],
            ['Qual cor simboliza esperança no Réveillon?', ['Verde', 'Branco', 'Amarelo', 'Roxo'], 0],
            ['Qual fruta é símbolo de fartura no Ano Novo?', ['Uva', 'Laranja', 'Banana', 'Maçã'], 0],
            ['Qual música natalina é considerada um clássico mundial?', ['Jingle Bells', 'Noite Feliz', 'Deck the Halls', 'Frosty'], 0],
            ['Quem foi Nicolau de Mira?', ['Bispo que inspirou Papai Noel', 'Rei Mago', 'Músico', 'Imperador'], 0],
            ['Qual país começou a tradição dos presentes?', ['Países Baixos', 'Alemanha', 'Brasil', 'Itália'], 0],
            ['Qual nome significa “Natal” em inglês?', ['Christmas', 'Xmas', 'Holyday', 'Festmas'], 0],
            ['De onde vem a palavra “Christmas”?', ['Cristo + Missa', 'Festa + Missa', 'Festa + Natal', 'Noite + Feliz'], 0],
            ['Qual é o idioma original de “Feliz Navidad”?', ['Espanhol', 'Alemão', 'Inglês', 'Francês'], 0],
            ['Qual figura enfeita a porta das casas no Natal?', ['Guirlanda', 'Estrela', 'Meia', 'Presépio'], 0],
            ['Quem inspirou o nome “Santa Claus”?', ['São Nicolau', 'São João', 'São Pedro', 'Santo Antônio'], 0],
            ['Em que país nasceu a tradição dos cartões natalinos?', ['Inglaterra', 'EUA', 'Alemanha', 'França'], 0],
            ['Quem escreveu a música “White Christmas”?', ['Irving Berlin', 'Bing Crosby', 'Frank Sinatra', 'Dean Martin'], 0],
            ['Qual é o país mais iluminado no Natal?', ['EUA', 'Alemanha', 'Brasil', 'França'], 0],
            ['Qual é o alimento típico do Natal no Brasil?', ['Chester', 'Sushi', 'Feijoada', 'Pizza'], 0],
            ['Qual alimento simboliza prosperidade no Ano Novo?', ['Lentilha', 'Pão', 'Arroz', 'Feijão'], 0],
            ['Por que se comem uvas no Ano Novo?', ['Simbolizam sorte', 'Simbolizam amor', 'Simbolizam alegria', 'Simbolizam fé'], 0],
            ['Qual superstição é comum na virada de ano?', ['Pular ondas', 'Cantar hinos', 'Dançar quadrilha', 'Pintar a casa'], 0],
            ['Qual flor vermelha é usada nas decorações de Natal?', ['Poinsétia', 'Rosa', 'Margarida', 'Orquídea'], 0],
            ['Quem visita as crianças que se comportam mal segundo o folclore europeu?', ['Krampus', 'Rena', 'Duende', 'Fada'], 0],
            ['Qual o nome do personagem maligno oposto ao Papai Noel?', ['Krampus', 'Balthazar', 'Snowman', 'Elf'], 0],
            ['Em que país surgiu a lenda do Krampus?', ['Áustria', 'Alemanha', 'Suíça', 'Espanha'], 0],
            ['Qual símbolo representa a eternidade nas decorações natalinas?', ['Guirlanda', 'Estrela', 'Meia', 'Boneco de neve'], 0],
            ['Por que se penduram meias na lareira?', ['Para receber presentes', 'Para secar', 'Para decorar', 'Por tradição militar'], 0],
            ['Qual personagem costuma dizer “Ho Ho Ho”?', ['Papai Noel', 'Duende', 'Boneco de Neve', 'Krampus'], 0],
            ['Quem canta “All I Want for Christmas Is You”?', ['Mariah Carey', 'Frank Sinatra', 'Michael Bublé', 'Dean Martin'], 0],
            ['Qual cidade é conhecida como “capital mundial do Natal”?', ['Rovaniemi', 'Berlim', 'Paris', 'Nova York'], 0],
            ['Rovaniemi está localizada em qual país?', ['Finlândia', 'Suécia', 'Noruega', 'Alemanha'], 0],
            ['Qual país tem tradição de desfiles natalinos com luzes?', ['EUA', 'Brasil', 'Portugal', 'Áustria'], 0],
            ['Qual país tem a maior árvore de Natal flutuante?', ['Brasil', 'Alemanha', 'EUA', 'Canadá'], 0],
            ['Qual cidade brasileira é conhecida por seu Natal Luz?', ['Gramado', 'São Paulo', 'Curitiba', 'Salvador'], 0],
            ['Qual flor é conhecida como “flor do Natal”?', ['Poinsétia', 'Girassol', 'Rosa', 'Margarida'], 0],
            ['O que significa o nome “Natal”?', ['Nascimento', 'Festa', 'Alegria', 'Esperança'], 0],
            ['Qual personagem vive no Polo Norte?', ['Papai Noel', 'Rena', 'Fada', 'Boneco'], 0],
            ['Qual é o nome da rena de nariz vermelho?', ['Rudolph', 'Dasher', 'Prancer', 'Comet'], 0],
            ['Quantos Reis Magos visitaram Jesus?', ['Três', 'Quatro', 'Dois', 'Cinco'], 0],
            ['Quem criou a tradição do presépio?', ['São Francisco de Assis', 'São Pedro', 'São João', 'Santo Antônio'], 0],
            ['Em que país surgiu a árvore de Natal?', ['Alemanha', 'EUA', 'França', 'Itália'], 0],
            ['Qual presente foi oferecido por Gaspar?', ['Incenso', 'Mirra', 'Ouro', 'Prata'], 0],
            ['Qual presente foi oferecido por Baltazar?', ['Mirra', 'Ouro', 'Incenso', 'Paz'], 0],
            ['Qual presente foi oferecido por Melchior?', ['Ouro', 'Incenso', 'Mirra', 'Paz'], 0],
            ['Qual flor vermelha simboliza o Natal?', ['Poinsétia', 'Rosa', 'Girassol', 'Orquídea'], 0],
            ['Qual fruta é símbolo de fartura no Ano Novo?', ['Uva', 'Banana', 'Pêssego', 'Laranja'], 0],
            ['Qual é a principal figura do Natal cristão?', ['Jesus Cristo', 'Papai Noel', 'Rei Mago', 'Rudolph'], 0],
            ['Qual flor é chamada de “estrela de Natal”?', ['Poinsétia', 'Tulipa', 'Rosa', 'Lírio'], 0],
            ['Qual música é tradicional nas missas de Natal?', ['Noite Feliz', 'Jingle Bells', 'Deck the Halls', 'Frosty'], 0],
            ['Em qual continente nasceu Jesus?', ['Ásia', 'Europa', 'África', 'América'], 0],
            ['Quem anunciou aos pastores o nascimento?', ['Anjos', 'Reis Magos', 'Papai Noel', 'Duendes'], 0],
            ['Em qual cidade Jesus nasceu?', ['Belém', 'Jerusalém', 'Roma', 'Nazaré'], 0],
            ['Em que país nasceu São Nicolau?', ['Turquia', 'Alemanha', 'Espanha', 'França'], 0],
            ['Qual é o símbolo mais usado no topo da árvore?', ['Estrela', 'Boneco', 'Meia', 'Guirlanda'], 0],
            ['Quem canta “Feliz Navidad”?', ['José Feliciano', 'Elvis Presley', 'Frank Sinatra', 'Dean Martin'], 0],
            ['Em que país foi criada a música “Feliz Navidad”?', ['Porto Rico', 'México', 'Brasil', 'Espanha'], 0],
            ['Qual cor simboliza prosperidade no Ano Novo?', ['Amarelo', 'Branco', 'Vermelho', 'Azul'], 0],
            ['Qual personagem lendário tem barba branca?', ['Papai Noel', 'Krampus', 'Duende', 'Anjo'], 0],
            ['Quem são os ajudantes do Papai Noel?', ['Duendes', 'Fadas', 'Anjos', 'Bonecos'], 0],
            ['O que simboliza a estrela de Belém?', ['Luz que guiou os Magos', 'Alegria', 'Paz', 'Fartura'], 0],
            ['Qual fruta tropical aparece no Natal brasileiro?', ['Uva', 'Manga', 'Banana', 'Abacaxi'], 0],
            ['Qual país é famoso por feiras de Natal ao ar livre?', ['Alemanha', 'EUA', 'França', 'Brasil'], 0],
            ['Qual animal representa humildade no presépio?', ['Jumento', 'Cavalo', 'Rena', 'Carneiro'], 0],
            ['Qual bebida quente é tradicional em países frios?', ['Chocolate quente', 'Chá', 'Leite', 'Vinho'], 0],
            ['Qual nome significa “anúncio” antes do Natal?', ['Advento', 'Epifania', 'Ressurreição', 'Pentecostes'], 0],
            ['Qual flor vermelha é símbolo de Natal?', ['Poinsétia', 'Lírio', 'Girassol', 'Rosa'], 0],
            ['O que significa Natal para os cristãos?', ['Nascimento de Jesus', 'Ano Novo', 'Fartura', 'Estação de neve'], 0],
            ['Quem recebeu a visita dos Reis Magos?', ['Jesus', 'José', 'Papai Noel', 'Pedro'], 0],
            ['Quem representa o amor e a doação no Natal?', ['Papai Noel', 'Krampus', 'Rei Mago', 'Duende'], 0],
            ['Qual presente representa a realeza de Jesus?', ['Ouro', 'Mirra', 'Incenso', 'Paz'], 0],
            ['Qual flor é chamada de “estrela de Natal”?', ['Poinsétia', 'Rosa', 'Tulipa', 'Lírio'], 0]
        ];

        foreach ($questions as $index => $q) {
            $number = $index + 1;

            // -----------------------------------------------------------------
            // 1. Evita cadastrar perguntas repetidas
            // -----------------------------------------------------------------
            $existing = Question::where('statement', $q[0])->first();
            if ($existing) {
                // pula essa pergunta pois já existe no banco
                continue;
            }

            // -----------------------------------------------------------------
            // 2. Sorteia a dificuldade de forma aleatória
            // -----------------------------------------------------------------
            $difficulty = array_column(Difficulty::cases(), 'value');
            $selectedDifficulty = $difficulty[rand(0, count($difficulty) - 1)];

            // -----------------------------------------------------------------
            // 3. Prepara e embaralha as alternativas mantendo a correta
            // -----------------------------------------------------------------
            $originalAnswers = [];
            foreach ($q[1] as $i => $text) {
                $originalAnswers[] = [
                    'text' => $text,
                    'is_correct' => ($i === $q[2]), // marca a correta original
                ];
            }

            // Embaralha as alternativas de forma segura
            shuffle($originalAnswers);

            // -----------------------------------------------------------------
            // 4. Cria a pergunta
            // -----------------------------------------------------------------
            $question = Question::create([
                'title' => "Pergunta {$number}",
                'statement' => $q[0],
                'difficulty' => $selectedDifficulty,
                'active' => true,
            ]);

            // -----------------------------------------------------------------
            // 5. Cadastra as alternativas com os rótulos A, B, C, D
            // -----------------------------------------------------------------
            foreach ($originalAnswers as $i => $alt) {
                Answer::create([
                    'question_id' => $question->id,
                    'label' => chr(65 + $i), // A, B, C, D
                    'text' => $alt['text'],
                    'is_correct' => $alt['is_correct'], // preserva a correta embaralhada
                ]);
            }
        }
    }
}
